---
- hosts: node2
  strategy: free
  gather_facts: true
  become: true
  tasks:
  - name: Setting Hostname
    hostname: name=node2.ansi.example.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Checking Sudoers Configuration
    lineinfile:
      path: /etc/sudoers
      regexp: '^# %users  localhost'
      insertafter: '^# %users  localhost'
      line: 'user ALL=(ALL) NOPASSWD: ALL'
      state: present
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Building host file
    copy:
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n192.168.55.59 repo.ansi.example.com repo\n192.168.55.60 control.ansi.example.com control\n192.168.55.61 node1.ansi.example.com node1\n192.168.55.62 node2.ansi.example.com node2\n192.168.55.63 node3.ansi.example.com node3"
      dest: /etc/hosts
      force: yes
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/rpms.repo
      block: |
       [rpms]
       name=rpms
       baseurl=http://repo/rpms/75rpms
       gpgcheck=0
       enabled=1
      create: yes
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
    tags: repo
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '       
         #           _            _           _           _        _       
         #          /\ \     _   /\ \        /\ \        /\ \    /\ \      
         #         /  \ \   /\_\/  \ \      /  \ \____  /  \ \  /  \ \     
         #        / /\ \ \_/ / / /\ \ \    / /\ \_____\/ /\ \ \/ /\ \ \    
         #       / / /\ \___/ / / /\ \ \  / / /\/___  / / /\ \_\/_/\ \ \   
         #      / / /  \/____/ / /  \ \_\/ / /   / / / /_/_ \/_/   / / /   
         #     / / /    / / / / /   / / / / /   / / / /____/\     / / /    
         #    / / /    / / / / /   / / / / /   / / / /\____\/    / / /  _  
         #   / / /    / / / / /___/ / /\ \ \__/ / / / /______   / / /_/\_\ 
         #  / / /    / / / / /____\/ /  \ \___\/ / / /_______\ / /_____/ / 
         #  \/_/     \/_/\/_________/    \/_____/\/__________/ \________/  
         '"#
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         "
...